/**
 * Tarmac Design System — Standalone Tailwind Preset
 * Generated from TDS token values for local development.
 * Replace with `require('@delhivery/tarmac/tailwind-preset')` when registry access is available.
 */
module.exports = {
  theme: {
    extend: {
      spacing: {
        'tds-0': '0px',
        'tds-2': '2px',
        'tds-4': '4px',
        'tds-6': '6px',
        'tds-8': '8px',
        'tds-12': '12px',
        'tds-14': '14px',
        'tds-16': '16px',
        'tds-20': '20px',
        'tds-24': '24px',
        'tds-32': '32px',
      },
      borderRadius: {
        'tds-none': '0px',
        'tds-sm': '2px',
        'tds-default': '4px',
        'tds-md': '8px',
        'tds-lg': '12px',
        'tds-xl': '16px',
        'tds-full': '999px',
      },
      fontFamily: {
        'tds-display': ['"Noto Sans"', 'sans-serif'],
        'tds-heading': ['"Noto Sans"', 'sans-serif'],
        'tds-body': ['"Noto Sans"', 'sans-serif'],
        'tds-caption': ['"Noto Sans"', 'sans-serif'],
      },
      colors: {
        'tds-surface-bg-primary-default': '#ffffff',
        'tds-surface-bg-coal-weakest': '#f9f9fb',
        'tds-surface-bg-coal-subtle': '#e0e3eb',
        'tds-surface-bg-coal-weak': '#eff1f5',
        'tds-surface-bg-primary-inverse-default': '#000000',
        'tds-surface-bg-primary-inverse-subtle': '#333333',
        'tds-surface-bg-blue-default': '#2396fb',
        'tds-surface-bg-blue-weakest': '#f0f8ff',
        'tds-surface-bg-legacy-blue-default': '#5b80f7',
        'tds-surface-bg-success-default': '#1ba86e',
        'tds-surface-bg-success-weakest': '#f4fbf8',
        'tds-surface-bg-error-default': '#dc143c',
        'tds-surface-bg-error-weakest': '#fdf2f4',
        'tds-surface-bg-warning-default': '#f5c828',
        'tds-surface-bg-warning-weakest': '#fefaec',
        'tds-surface-bg-dlv-red-default': '#ed1b36',
        'tds-text-heading-primary': '#121212',
        'tds-text-body-primary': '#2b2b2b',
        'tds-text-body-secondary': '#3b3b3b',
        'tds-text-body-disabled': '#cdcbcb',
        'tds-text-caption-primary': '#454545',
        'tds-text-caption-secondary': '#666666',
        'tds-text-info-blue-primary': '#2396fb',
        'tds-text-success-primary': '#1ba86e',
        'tds-text-error-primary': '#dc143c',
        'tds-text-warning-primary': '#7b6414',
        'tds-text-body-inverse-primary': '#e6e6e6',
        'tds-text-heading-inverse-only-white': '#ffffff',
        'tds-border-neutral-primary': '#e6e6e6',
        'tds-border-neutral-secondary': '#d9d9d9',
        'tds-border-neutral-disabled': '#ededed',
        'tds-border-info-primary': '#48a7fc',
        'tds-border-success-primary': '#41b686',
        'tds-border-error-primary': '#e23b5d',
        'tds-border-warning-primary': '#f5c828',
        'tds-icon-body-primary': '#2b2b2b',
        'tds-icon-body-disabled': '#cdcbcb',
        'tds-icon-info-blue-primary': '#2396fb',
        'tds-icon-success-primary': '#1ba86e',
        'tds-icon-error-primary': '#dc143c',
        'tds-icon-warning-primary': '#7b6414',
        'tds-alpha-black-50': 'rgba(0,0,0,0.05)',
        'tds-alpha-black-100': 'rgba(0,0,0,0.10)',
        'tds-alpha-black-200': 'rgba(0,0,0,0.20)',
        'tds-alpha-black-300': 'rgba(0,0,0,0.40)',
        'tds-alpha-white-100': 'rgba(255,255,255,0.10)',
        'tds-alpha-white-200': 'rgba(255,255,255,0.20)',
        'tds-alpha-white-300': 'rgba(255,255,255,0.40)',
      },
    },
  },
};
